services:
  - type: web
    name: capital-hosiery-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
